export default {
  products: [
    {
      _id: "1",
      name: "Slim-Shirt",
      category: "Shirt",
      image: "/images/Slim-Fit-Street.jpg.webp",
      price: 60,
      brand: " faststreet",
      rating: 4.5,
      numReviews: 10,
      countInStock: 8,
    },
    {
      _id: "2",
      name: "White-Shirt",
      category: "Shirts",
      image: "/images/Slim-Fit-Street.jpg.webp",
      price: 60,
      brand: " faststreet",
      rating: 4.0,
      numReviews: 16,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "Slim-Pant",
      category: "Pants",
      image: "/images/Slim-Fit-Street.jpg.webp",
      price: 60,
      brand: " faststreet",
      rating: 3,
      numReviews: 7,
      countInStock: 4,
    },
  ],
};
